# react app / frontend
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://{default}/":
  type: upstream
  upstream: "frontend:http"

# drupal 8 / API
"https://api.{default}/":
    type: upstream
    upstream: "api:http"

"https://api.{default}/jsonapi/":
  type: upstream
  upstream: "api:http"