# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.2
    disk: 2048

cache:
    type: redis:5.0

search:
    type: solr:8.4
    disk: 256
    configuration:
      cores:
        maincore:
          conf_dir: !archive "solr_8.x_config/"
      endpoints:
        main:
          core: maincore